"""Reusable helpers for the VOD2Video project."""

from .clip_features import (
    AudioExtractionConfig,
    AudioToolStatus,
    DEFAULT_FEATURE_COLUMNS,
    ClipFeatureExtractionError,
    ClipSamplingConfig,
    FeatureManifestSummary,
    build_feature_manifest,
    build_feature_manifest_summary,
    extract_clip_features,
    extract_audio_features,
    extract_visual_features,
    load_feature_source_manifest,
    make_audio_fallback_features,
    resolve_audio_tool_status,
    write_feature_manifest_outputs,
)
from .dataset_loader import (
    DatasetSummary,
    DatasetValidationError,
    LabeledDatasetSource,
    LoadedDataset,
    format_summary,
    load_labeled_dataset,
)
from .dataset_split import (
    DatasetSplit,
    DatasetSplitError,
    SplitConfig,
    SplitSummary,
    format_split_summaries,
    split_labeled_dataset,
    write_split_manifests,
)
from .metrics import BinaryClassificationMetrics, compute_binary_classification_metrics
from .models import MLPBaselineModel, build_model
from .inference import (
    InferenceError,
    InferenceSummary,
    LoadedInferenceCheckpoint,
    build_prediction_dataframe,
    load_feature_manifest_for_inference,
    load_inference_checkpoint,
    score_feature_manifest,
    write_inference_outputs,
)
from .prediction_review import (
    PredictionReviewError,
    PredictionReviewSummary,
    build_prediction_review_summary,
    load_prediction_review_csv,
    merge_review_labels,
    prepare_predictions_for_review,
    review_prediction_csv,
    write_prediction_review_outputs,
)
from .training import train_model, train_one_epoch, validate_model
from .training_config import CheckpointConfig, DataConfig, ModelConfig, TrainingConfig
from .training_data import (
    DEFAULT_FEATURE_NAMES,
    DatasetBundle,
    SplitManifestDataset,
    TrainingDataError,
    build_dataloaders_from_manifest,
    load_split_manifest,
    prepare_training_manifest,
)
from .visualization import (
    VisualizationArtifacts,
    VisualizationError,
    build_confusion_matrix_table,
    build_epoch_metrics_table,
    build_metrics_comparison_table,
    build_metrics_table,
    build_review_summary_table,
    generate_visualization_artifacts,
)

__all__ = [
    "BinaryClassificationMetrics",
    "AudioExtractionConfig",
    "AudioToolStatus",
    "CheckpointConfig",
    "ClipFeatureExtractionError",
    "ClipSamplingConfig",
    "DEFAULT_FEATURE_NAMES",
    "DEFAULT_FEATURE_COLUMNS",
    "DataConfig",
    "DatasetBundle",
    "DatasetSummary",
    "DatasetValidationError",
    "DatasetSplit",
    "DatasetSplitError",
    "LabeledDatasetSource",
    "FeatureManifestSummary",
    "InferenceError",
    "InferenceSummary",
    "LoadedDataset",
    "LoadedInferenceCheckpoint",
    "MLPBaselineModel",
    "ModelConfig",
    "PredictionReviewError",
    "PredictionReviewSummary",
    "SplitConfig",
    "SplitManifestDataset",
    "SplitSummary",
    "TrainingConfig",
    "TrainingDataError",
    "VisualizationArtifacts",
    "VisualizationError",
    "build_dataloaders_from_manifest",
    "build_confusion_matrix_table",
    "build_epoch_metrics_table",
    "build_prediction_dataframe",
    "build_feature_manifest",
    "build_feature_manifest_summary",
    "build_metrics_comparison_table",
    "build_metrics_table",
    "build_model",
    "compute_binary_classification_metrics",
    "build_review_summary_table",
    "extract_audio_features",
    "extract_clip_features",
    "extract_visual_features",
    "format_summary",
    "format_split_summaries",
    "generate_visualization_artifacts",
    "load_labeled_dataset",
    "load_feature_source_manifest",
    "load_feature_manifest_for_inference",
    "load_prediction_review_csv",
    "load_inference_checkpoint",
    "load_split_manifest",
    "merge_review_labels",
    "prepare_training_manifest",
    "prepare_predictions_for_review",
    "build_prediction_review_summary",
    "review_prediction_csv",
    "score_feature_manifest",
    "split_labeled_dataset",
    "make_audio_fallback_features",
    "resolve_audio_tool_status",
    "train_model",
    "train_one_epoch",
    "validate_model",
    "write_inference_outputs",
    "write_prediction_review_outputs",
    "write_feature_manifest_outputs",
    "write_split_manifests",
]
